fix: use delegate parameter tableView instead of non-existent property
Fix compilation error where self.tableView was used but doesn't exist.
Use the tableView parameter passed to tableView(_:cellForRowAt:) instead.

Error: Value of type 'UIViewController' has no member 'tableView'
Location: TLPhotosPickerViewController.swift:1267:40